include_guard = "_SYS_IOCTL_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=linux" = "__linux__"
"target_os=redox" = "__redox__"
"target_os=dragonos" = "__dragonos__"

[enum]
prefix_with_name = true

[export]
include = ["sgttyb", "winsize"]
